---
title: "Simulations"
output: html_document
date: "2024-04-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('fBasics')
library('Matrix')
library("matrixcalc")
```


# Jacobian matroids

## 3 nodes

```{r}
# Initialization
n <- 3
Lambda <- rbind(c(0.5,0,0.65),c(0,0.6,0.4),c(0.4,0.8,0.7))  # Changable coefficients
# Lambda <- matrix(rep(1,9),nrow=3)
# Lambda <- matrix(runif(9,0,1),nrow=3)

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

# Calculate J
Sig_Lam <- Sigma %*% Lambda
B <- rbind(c(Sig_Lam[1,],0,0,0,0,0,0),c(0,0,0,Sig_Lam[1,],0,0,0),c(0,0,0,0,0,0,Sig_Lam[1,]),c(Sig_Lam[2,],0,0,0,0,0,0),c(0,0,0,Sig_Lam[2,],0,0,0),c(0,0,0,0,0,0,Sig_Lam[2,]),c(Sig_Lam[3,],0,0,0,0,0,0),c(0,0,0,Sig_Lam[3,],0,0,0),c(0,0,0,0,0,0,Sig_Lam[3,])) + Sig_Lam %x% diag(n)
B <- rbind(B, c(1,0,0,0,1,0,0,0,1))
# B_prime <- B[-which(t(Lambda) == 0),]
J <- B %*% solve(diag(n**2)-(Lambda %x% Lambda))
J_G <- J[-which(t(Lambda) == 0),]

Sigma

inv_Sigma

# J_G
J

# rankMatrix(J_G)
rankMatrix(J)
```

```{r}
# Initialization
n <- 3
Lambda <- rbind(c(0.5,0.9,0),c(0,0.6,0),c(0,0.9,0.7))  # Changable coefficients

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

# Lambda_prime
Lambda_prime <- chol(Sigma)

# Calculate J_prime
Sig_Lam_prime <- Sigma %*% Lambda_prime
B <- rbind(c(Sig_Lam_prime[1,],0,0,0,0,0,0),c(0,0,0,Sig_Lam_prime[1,],0,0,0),c(0,0,0,0,0,0,Sig_Lam_prime[1,]),c(Sig_Lam_prime[2,],0,0,0,0,0,0),c(0,0,0,Sig_Lam_prime[2,],0,0,0),c(0,0,0,0,0,0,Sig_Lam_prime[2,]),c(Sig_Lam_prime[3,],0,0,0,0,0,0),c(0,0,0,Sig_Lam_prime[3,],0,0,0),c(0,0,0,0,0,0,Sig_Lam_prime[3,])) + Sig_Lam_prime %x% diag(n)
B <- rbind(B, c(1,0,0,0,1,0,0,0,1))
B_prime <- B[-which(t(Lambda_prime) == 0),]
J_prime <- B %*% solve(diag(n**2)-(Lambda_prime %x% Lambda_prime))
J_G_prime <- J_prime[-which(t(Lambda_prime) == 0),]

Sigma

inv_Sigma

J_G_prime

rankMatrix(J_G_prime)
```


## 4 nodes

```{r}
# Initialization
n <- 4
Lambda_1 <- rbind(c(0.5,0.7,0,0),c(0,0.6,0,0),c(0,0,0.4,0.9),c(0,0,0,0.3))  # Changable coefficients
Lambda_2 <- rbind(c(0.5,0.7,0,0.9),c(0,0.6,0.4,0),c(0,0,0.4,0),c(0,0,0,0.3))  # Changable coefficients

omega <- 1

# Calculate Sigma
vec_Sigma_1 <- solve(diag(n**2)-(Lambda_1 %x% Lambda_1)) %*% vec(omega * diag(n))
Sigma_1 <- matrix(vec_Sigma_1, nrow = n)
vec_Sigma_2 <- solve(diag(n**2)-(Lambda_2 %x% Lambda_2)) %*% vec(omega * diag(n))
Sigma_2 <- matrix(vec_Sigma_2, nrow = n)

# Calculate J
Sig_Lam_1 <- Sigma_1 %*% Lambda_1
B_1 <- rbind(c(Sig_Lam_1[1,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_1[1,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_1[1,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_1[1,]),c(Sig_Lam_1[2,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_1[2,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_1[2,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_1[2,]),c(Sig_Lam_1[3,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_1[3,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_1[3,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_1[3,]),c(Sig_Lam_1[4,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_1[4,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_1[4,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_1[4,])) + Sig_Lam_1 %x% diag(n)
B_1 <- rbind(B_1, c(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1))
J_1 <- B_1 %*% solve(diag(n**2)-(Lambda_1 %x% Lambda_1))
B_1_prime <- B_1[-which(t(Lambda_1) == 0),]
J_G_1 <- J_1[-which(t(Lambda_1) == 0),]

Sig_Lam_2 <- Sigma_2 %*% Lambda_2
B_2 <- rbind(c(Sig_Lam_2[1,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_2[1,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_2[1,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_2[1,]),c(Sig_Lam_2[2,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_2[2,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_2[2,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_2[2,]),c(Sig_Lam_2[3,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_2[3,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_2[3,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_2[3,]),c(Sig_Lam_2[4,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam_2[4,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam_2[4,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam_2[4,])) + Sig_Lam_2 %x% diag(n)
B_2 <- rbind(B_2, c(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1))
J_2 <- B_2 %*% solve(diag(n**2)-(Lambda_2 %x% Lambda_2))
J_G_2 <- J_2[-which(t(Lambda_2) == 0),]

J_G_1
J_G_2

rankMatrix(J_G_1)
rankMatrix(J_G_2)
```

```{r}
# Initialization
n <- 4
Lambda <- rbind(c(0.3,0.8,0,0),c(0,0.5,0,0),c(0,0.3,0.6,0),c(0,0,0.7,0.9))  # Changable coefficients
# Lambda_prime <- rbind(c(0.3,0,0,0),c(0,0.5,0,0),c(0,0,0.6,0),c(0,0,0,0.9))

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

# Calculate J
Sig_Lam <- Sigma %*% Lambda
B <- rbind(c(Sig_Lam[1,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam[1,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam[1,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam[1,]),c(Sig_Lam[2,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam[2,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam[2,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam[2,]),c(Sig_Lam[3,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam[3,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam[3,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam[3,]),c(Sig_Lam[4,],rep(0L,3*n)),c(rep(0L,n),Sig_Lam[4,],rep(0L,2*n)),c(rep(0L,2*n),Sig_Lam[4,],rep(0L,n)),c(rep(0L,3*n),Sig_Lam[4,])) + Sig_Lam %x% diag(n)
B <- rbind(B, c(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1))
J <- B %*% solve(diag(n**2)-(Lambda %x% Lambda))
B_prime <- B[-which(t(Lambda) == 0),]
J_G <- J[-which(t(Lambda) == 0),]

Lambda

Sigma

inv_Sigma

J_G

rankMatrix(J_G)
```

## 5 nodes

```{r}
# Initialization
n <- 5
Lambda <- rbind(c(0.7,0.9,0.6,0.3,0), c(0.3,0.8,0,0,0.7),c(0.5,0,0.4,0,0),c(0.65,0,0,0.9,0), c(0,0.8,0,0,0.5))  # Changable coefficients
# Lambda_prime <- rbind(c(0.3,0.8,0,0,0),c(0.7,0.5,0.4,0,0),c(0,0.9,0.6,0.3,0),c(0,0,0.65,0.9,0.6), c(0,0,0,0.8,0.5))
# Lambda_prime <- rbind(c(0.3,0,0.8,0,0),c(0,0.5,0.4,0,0),c(0.7,0.9,0.6,0.3,0.4),c(0,0,0.65,0.9,0), c(0,0,0.8,0,0.5)) 

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
# inv_Sigma <- solve(Sigma)

# Calculate J
# Sig_Lam <- Sigma %*% Lambda
Sig_Lam <- rbind(c(0.3,0.6,0.5,0.9,0),c(0,0.8,0.6,0,0),c(0,0,0.5,0.4,0),c(0,0,0,0.7,0.9), c(0,0,0.5,0.89,0))
B <- rbind(c(Sig_Lam[1,],rep(0L,4*n)),c(rep(0L,n),Sig_Lam[1,],rep(0L,3*n)),c(rep(0L,2*n),Sig_Lam[1,],rep(0L,2*n)),c(rep(0L,3*n),Sig_Lam[1,],rep(0L,n)),c(rep(0L,4*n),Sig_Lam[1,]), 
           c(Sig_Lam[2,],rep(0L,4*n)),c(rep(0L,n),Sig_Lam[2,],rep(0L,3*n)),c(rep(0L,2*n),Sig_Lam[2,],rep(0L,2*n)),c(rep(0L,3*n),Sig_Lam[2,],rep(0L,n)),c(rep(0L,4*n),Sig_Lam[2,]), 
           c(Sig_Lam[3,],rep(0L,4*n)),c(rep(0L,n),Sig_Lam[3,],rep(0L,3*n)),c(rep(0L,2*n),Sig_Lam[3,],rep(0L,2*n)),c(rep(0L,3*n),Sig_Lam[3,],rep(0L,n)),c(rep(0L,4*n),Sig_Lam[3,]), 
           c(Sig_Lam[4,],rep(0L,4*n)),c(rep(0L,n),Sig_Lam[4,],rep(0L,3*n)),c(rep(0L,2*n),Sig_Lam[4,],rep(0L,2*n)),c(rep(0L,3*n),Sig_Lam[4,],rep(0L,n)),c(rep(0L,4*n),Sig_Lam[4,]), 
           c(Sig_Lam[5,],rep(0L,4*n)),c(rep(0L,n),Sig_Lam[5,],rep(0L,3*n)),c(rep(0L,2*n),Sig_Lam[5,],rep(0L,2*n)),c(rep(0L,3*n),Sig_Lam[5,],rep(0L,n)),c(rep(0L,4*n),Sig_Lam[5,])) + Sig_Lam %x% diag(n)
B <- rbind(B, c(1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1))
# J <- B %*% solve(diag(n**2)-(Lambda %x% Lambda))
B_prime <- B[-which(t(Lambda) == 0),-c(6,11,12,16,17,18,21,22,23,24)]
B_prime <- B_prime[c(1,5,8,10,2,6,12,3,9,4,11,7,13,14),c(1,2,3,4,6,7,8,10,11,13,14,9,12,15)]
# J_G <- J[-which(t(Lambda_prime) == 0),]
# J_G <- J[-which(t(Lambda_prime) == 0), -c(6,11,12,16,17,18,21,22,23,24)]
# J_G <- J_G[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14),]

# J_G[J_G < 1e-10] <- 0

rankMatrix(B_prime)

# B_prime <-B_prime[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14), c(1,2,6,7,8,10,11,12,13,14,4,5,9,15,3)]
```



# Upper triangular

```{r}
# Initialization
n <- 3
Lambda <- rbind(c(0.5,0.7,0),c(0,0.9,0),c(0,0.8,0.4))  # Changable coefficients

omega <- 1

vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)

# Check if Sigma - omega * I is positive definite
if (is.positive.definite(round(Sigma - omega * diag(n),10)) && is.positive.definite(round(Sigma,10))) {
  Lambda_rec <- solve(chol(Sigma)) %*% chol(Sigma - omega * diag(n))
  P <- chol(Sigma) %*% Lambda %*% solve(chol(Sigma - omega * diag(n)))
}else{
  print("Sigma - omega * I or Sigma is not positive definite!")
}

print("Lambda:")
Lambda
print("Recovered Lambda:")
Lambda_rec
print("Orthogonal matrix:")
P
```


## 6 nodes

```{r}
# Initialization
n <- 6
Lambda <- rbind(c(0.3,0.9,0,0,0,0.8),c(0.4,0.5,0.4,0,0,0),c(0,0.9,0.6,0.4,0,0),c(0,0,0.3,0.9,0.65,0), c(0,0,0,0.67,0.5,0.8), c(0.2,0,0,0,0.8,0.4))  # Changable coefficients
# Lambda_prime <- rbind(c(0.3,0.9,0.8,0.9,0,0),c(0.4,0.5,0.4,0,0.7,0),c(0.7,0.9,0.6,0,0,0.4),c(0.65,0,0,0.9,0,0), c(0,0.8,0,0,0.5,0), c(0,0,0.2,0,0,0.4))
# Lambda_prime <- rbind(c(0.3,0,0,0,0),c(0,0.5,0,0,0),c(0,0,0.6,0,0),c(0,0,0,0.9,0), c(0,0,0,0,0.5))

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
# inv_Sigma <- solve(Sigma)

# Calculate J
Sig_Lam <- Sigma %*% Lambda
# Sig_Lam <- rbind(c(0.3,0,0,0,0,0.9),c(0.8,0.6,0,0,0,0.6),c(0,0.8,0,0.5,0,0.4),c(0,0.7,0.8,0,0,0.3), c(0.6,0,0,0,0.5,0.8), c(0.3,0.5,0.6,0.2,0.9,0.8))
B <- rbind(c(Sig_Lam[1,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[1,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[1,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[1,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[1,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[1,]), 
           c(Sig_Lam[2,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[2,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[2,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[2,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[2,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[2,]), 
           c(Sig_Lam[3,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[3,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[3,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[3,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[3,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[3,]), 
           c(Sig_Lam[4,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[4,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[4,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[4,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[4,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[4,]), 
           c(Sig_Lam[5,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[5,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[5,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[5,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[5,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[5,]),
           c(Sig_Lam[6,],rep(0L,5*n)),c(rep(0L,n),Sig_Lam[6,],rep(0L,4*n)),c(rep(0L,2*n),Sig_Lam[6,],rep(0L,3*n)),c(rep(0L,3*n),Sig_Lam[6,],rep(0L,2*n)),c(rep(0L,4*n),Sig_Lam[6,],rep(0L,n)),c(rep(0L,5*n),Sig_Lam[6,])) + Sig_Lam %x% diag(n)
B <- rbind(B, c(1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1))
# J <- B %*% solve(diag(n**2)-(Lambda %x% Lambda))
B_prime <- B[-which(t(Lambda) == 0),-c(7,13,14,19,20,21,25,26,27,28,31,32,33,34,35)] # Remove redundant rows and columns
# B_prime <- B_prime[,c(1,2,3,4,5,7,8,9,10,12,13,14,16,17,19,6,11,15,18,20,21)] # Move columns correspond to node 6 to the end
# B_prime <- B_prime[c(1,2,4,5,7,8,9,10,11,12,13,14,15,19,3,6,16,17,18),c(1,3,2,7,4,6,11,13,14,10,8,12,5,15,9,16,17,18,19,20,21)] # Move the rows and columns such that 1-5 is upper triangular
# J_G <- J[-which(t(Lambda_prime) == 0),]
# J_G <- J[-which(t(Lambda_prime) == 0), -c(6,11,12,16,17,18,21,22,23,24)]
# J_G <- J_G[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14),]

# J_G[J_G < 1e-10] <- 0

rankMatrix(B_prime)

# B_prime <-B_prime[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14), c(1,2,6,7,8,10,11,12,13,14,4,5,9,15,3)]
```


## 8 nodes

```{r}
n <- 8
Lambda <- rbind(c(0.3,0,0.9,0.34,0.4,0.9,0.7,0.2),c(0,0.5,0.4,0.43,0.9,0.7,0.21,0.46),c(0.7,0.9,0.5,0.35,0,0,0,0),c(0.9,0.7,0.76,0.65,0,0,0,0), c(0.3,0.7,0,0,0.5,0,0,0), c(0.2,0.3,0,0,0,0.4,0,0), c(0.4,0.3,0,0,0,0,0.9,0), c(0.3,0.7,0,0,0,0,0,0.5))  # Changable coefficients
# Lambda_prime <- rbind(c(0.3,0.8,0,0,0),c(0.7,0.5,0.4,0,0),c(0,0.9,0.6,0.3,0),c(0,0,0.65,0.9,0.6), c(0,0,0,0.8,0.5))
# Lambda_prime <- rbind(c(0.3,0,0,0,0),c(0,0.5,0,0,0),c(0,0,0.6,0,0),c(0,0,0,0.9,0), c(0,0,0,0,0.5))

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
# inv_Sigma <- solve(Sigma)

# Calculate J
Sig_Lam <- Sigma %*% Lambda
# Sig_Lam <- rbind(c(0.3,0,0.27,0.34,0.8,0.45,0,0),c(0,0.5,0,0.43,0.9,0.7,0.9,0),c(0,0,0.5,0,0.9,0,0,0),c(0,0,0,0.65,0,0.7,0,0), c(0,0,0,0,0.5,0,0.6,0), c(0,0,0,0,0,0.4,0,0.8), c(0,0,0,0,0,0,0.9,0), c(0,0,0,0,0.8,0,0,0.5))
B <- rbind(c(Sig_Lam[1,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[1,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[1,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[1,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[1,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[1,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[1,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[1,]),
           c(Sig_Lam[2,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[2,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[2,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[2,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[2,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[2,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[2,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[2,]),
           c(Sig_Lam[3,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[3,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[3,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[3,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[3,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[3,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[3,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[3,]),
           c(Sig_Lam[4,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[4,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[4,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[4,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[4,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[4,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[4,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[4,]),
           c(Sig_Lam[5,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[5,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[5,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[5,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[5,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[5,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[5,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[5,]),
           c(Sig_Lam[6,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[6,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[6,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[6,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[6,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[6,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[6,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[6,]),
           c(Sig_Lam[7,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[7,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[7,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[7,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[7,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[7,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[7,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[7,]),
           c(Sig_Lam[8,],rep(0L,7*n)),c(rep(0L,n),Sig_Lam[8,],rep(0L,6*n)),c(rep(0L,2*n),Sig_Lam[8,],rep(0L,5*n)),c(rep(0L,3*n),Sig_Lam[8,],rep(0L,4*n)),c(rep(0L,4*n),Sig_Lam[8,],rep(0L,3*n)),c(rep(0L,5*n),Sig_Lam[8,],rep(0L,2*n)), c(rep(0L,6*n),Sig_Lam[8,],rep(0L,n)), c(rep(0L,7*n),Sig_Lam[8,])) + Sig_Lam %x% diag(n)
B <- rbind(B, as.vector(diag(n)))
# J <- B %*% solve(diag(n**2)-(Lambda %x% Lambda))

B_prime <- B[-which(t(Lambda) == 0),-c(9,17,18,25,26,27,33,34,35,36,41,42,43,44,45,49,50,51,52,53,54,57,58,59,60,61,62,63)]
# B_prime <- B_prime[c(1,9,17,20,23,26,29,32,2,10,18,21,24,27,30,33,3,11,19,4,12,22,5,13,25,6,14,28,7,15,31,8,16,34,35),c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,22,23,24,27,28,29,31,32,33,20,25,34,21,26,30,36,19,35)]
# B_prime <- B_prime[,c(1,2,3,4,5,7,8,9,10,12,13,14,16,17,19,6,11,15,18,20,21)] # Move columns correspond to node 6 to the end
# B_prime <- B_prime[c(1,2,4,5,7,8,9,10,11,12,13,14,15,19,3,6,16,17,18),c(1,3,2,7,4,6,11,13,14,10,8,12,5,15,9,16,17,18,19,20,21)] # Move the rows and columns such that 1-5 is upper triangular
# J_G <- J[-which(t(Lambda_prime) == 0),]
# J_G <- J[-which(t(Lambda_prime) == 0), -c(6,11,12,16,17,18,21,22,23,24)]
# J_G <- J_G[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14),]

# J_G[J_G < 1e-10] <- 0

# B_prime <- B_prime[-c(9),]
rankMatrix(B_prime)

# B_prime <-B_prime[c(1,3,2,4,6,5,7,9,8,10,12,11,13,14), c(1,2,6,7,8,10,11,12,13,14,4,5,9,15,3)]
```



# Maximal classes

Remark: setequal(a,b), setdiff(a,b)

## Algorithm 1: graph -> maximal classes

```{r}
library("igraph")
```

```{r}
n <- 6
# g <- make_graph(edges = c(2, 1, 3, 1, 1, 4, 6, 4, 4, 5), n = n, directed = TRUE)
g <- make_graph(edges = c(2, 1, 3, 1, 6, 4, 4, 5, 5, 6), n = n, directed = TRUE)

lbs <- rep(0L,n) # Labels for the nodes, global variable
maxc <- matrix(0,n,n) # Maximal classes, global variable
```

```{r}
search_maximal_class <- function(adj_g,i,j) {
  lbs[i] <<- 1
  maxc[j,i] <<- i
  
  for(w in 1:n) {
    if(adj_g[i,w] == 1 & !(w %in% maxc[j,])) {
      search_maximal_class(adj_g,w,j)
    }
  }
}

get_maximal_class <- function(g) {
  lbs <<- rep(0L,n)
  maxc <<- matrix(0,n,n)
  adj_g <- as_adjacency_matrix(g)
  
  num <- 0
  
  for(i in 1:n) {
    if(all(adj_g[,i] == 0)) {
      search_maximal_class(adj_g,i,i)
      num <- num + 1
    }
  }
  
  for(i in 1:n){
    # Loops
    if(lbs[i] == 0) {
      search_maximal_class(adj_g,i,i)
      num <- num + 1
    }
  }
  
  print(paste("Number of maximal classes: ", num))
  print(maxc)
}
```

```{r}
get_maximal_class(g)
```

## Algorithm 2: maximal classes -> graph

```{r}
find_source <- function(a,b) {
  target <- intersect(a,b)
  source_1 <- setdiff(a,b)
  source_2 <- setdiff(b,a)
  
  if(length(source_1) != 0 & length(source_2) != 0) {
    edgs <<- append(edgs, list(list(source_1,target)))
    edgs <<- append(edgs, list(list(source_2,target)))
  }else {
    print("There is something wrong with maximal classes.")
  }
}

update_edges <- function(c) {
  del_edgs <- c()
  for(i in 1:length(edgs)) {
    if(length(intersect(edgs[[c(i,2)]],c)) != 0){
        find_source(edgs[[c(i,2)]],c)
        edgs <<- append(edgs, list(list(edgs[[c(i,1)]],setdiff(edgs[[c(i,2)]],c))))
        del_edgs <- c(del_edgs, i)
    }
  }
  edgs <<- edgs[-del_edgs]
  edgs <<- unique(edgs)
}

find_graph <- function(maxc) {
  num_maxc <- length(maxc)
  find_source(maxc[[1]],maxc[[2]])
  if(length(maxc) > 2) {
    for(i in 3:length(maxc)) {
      update_edges(maxc[[i]])
    }
  }
}
```

```{r}
edgs <- list() # List of edges recovered
maxc <- list(c(1,2,4,5),c(1,3,4,5),c(4,5,6))
# maxc <- list(c(2,1,4,5,6),c(3,1,4,5,6))
find_graph(maxc)
```

# The study of B_G

## \lambda_{ij}\lambda_{ji} = 0, i\neq j

```{r}
# Initialization
n <- 3
Lambda <- rbind(c(0.5,0.9,0.8),c(0,0.6,0),c(0,0,0.7))  # Changable coefficients
n_edges <- sum(Lambda!=0) - n

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

Sig_Lam <- Sigma %*% Lambda

# \lambda_{ij}\lambda_{ji} = 0, i\neq j
B_G <- matrix(0, n_edges + 1, n_edges + 1)
coor_edges <- which(Lambda != 0, arr.ind = T)
coor_edges <- coor_edges[which(coor_edges[,1]!=coor_edges[,2]),]

row_ind <- rbind(coor_edges, c(0,0))
col_ind <- rbind(coor_edges, c(2,3))    # Changeable

for (i in 1:n_edges) {
  for (j in 1:(n_edges+1)) {
    if (row_ind[i,2] == col_ind[j,1]) {
      # j = a
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,2]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,2]]
    }
    
    if (row_ind[i,2] == col_ind[j,2]) {
      # j = b
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,1]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,1]]
    }
  }
}

for (j in 1:(n_edges+1)) {
  B_G[n_edges+1,j] <- Sig_Lam[col_ind[j,1],col_ind[j,2]] * (Sig_Lam[col_ind[j,1],col_ind[j,1]] ** (-1)) + Sig_Lam[col_ind[j,2],col_ind[j,1]] * (Sig_Lam[col_ind[j,2],col_ind[j,2]] ** (-1))
}
```


```{r}
# Initialization
n <- 4
Lambda <- rbind(c(0.3,0.8,0,0.6),c(0,0.5,0.9,0.8),c(0,0,0.6,0),c(0,0,0,0.9))  # Changable coefficients
n_edges <- sum(Lambda!=0) - n

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

Sig_Lam <- Sigma %*% Lambda

# \lambda_{ij}\lambda_{ji} = 0, i\neq j
B_G <- matrix(0, n_edges + 1, n_edges + 1)
coor_edges <- which(Lambda != 0, arr.ind = T)
coor_edges <- coor_edges[which(coor_edges[,1]!=coor_edges[,2]),]

row_ind <- rbind(coor_edges, c(0,0))
col_ind <- rbind(coor_edges, c(1,3))    # Changeable
# col_ind <- rbind(c(1,2),c(1,3),c(2,4),c(1,4))

########################################################################
Lambda <- rbind(c(0.3,0.5,0,0),c(0,0.5,0.9,0),c(0,0,0.6,0),c(0,0,0,0.9))
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)
Sig_Lam <- Sigma %*% Lambda
########################################################################

for (i in 1:n_edges) {
  for (j in 1:(n_edges+1)) {
    if (row_ind[i,2] == col_ind[j,1]) {
      # j = a
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,2]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,2]]
    }
    
    if (row_ind[i,2] == col_ind[j,2]) {
      # j = b
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,1]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,1]]
    }
  }
}

for (j in 1:(n_edges+1)) {
  B_G[n_edges+1,j] <- Sig_Lam[col_ind[j,1],col_ind[j,2]] * (Sig_Lam[col_ind[j,1],col_ind[j,1]] ** (-1)) + Sig_Lam[col_ind[j,2],col_ind[j,1]] * (Sig_Lam[col_ind[j,2],col_ind[j,2]] ** (-1))
}
```

## \lambda_{ij}\lambda_{ji} \neq 0, \exists i\neq j

```{r}
# Initialization
n <- 3
Lambda <- rbind(c(0.5,0.9,0),c(0.7,0.6,0.9),c(0,0.8,0.7))  # Changable coefficients
n_edges <- sum(Lambda!=0) - n

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

Sig_Lam <- Sigma %*% Lambda

# \lambda_{ij}\lambda_{ji} = 0, i\neq j
B_G <- matrix(0, n_edges + 1, n_edges + 1)

row_ind <- rbind(c(1,2), c(2,1), c(2,3), c(3,2), c(0,0))
col_ind <- rbind(c(1,2), c(2,3), c(1,3))    # Changeable

for (i in 1:n_edges) {
  for (j in 1:3) {
    if (row_ind[i,2] == col_ind[j,1]) {
      # j = a
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,2]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,2]]
    }
    
    if (row_ind[i,2] == col_ind[j,2]) {
      # j = b
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,1]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,1]]
    }
  }
}

for (j in 1:3) {
  B_G[n_edges+1,j] <- Sig_Lam[col_ind[j,1],col_ind[j,2]] * (Sig_Lam[col_ind[j,1],col_ind[j,1]] ** (-1)) + Sig_Lam[col_ind[j,2],col_ind[j,1]] * (Sig_Lam[col_ind[j,2],col_ind[j,2]] ** (-1))
}
```


```{r}
n <- 4
Lambda <- rbind(c(0.3,0.8,0,0),c(0.4,0.5,0.7,0),c(0,0.8,0.6,0.7),c(0,0,0.5,0.9))  # Changable coefficients
n_edges <- sum(Lambda!=0) - n

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

Sig_Lam <- Sigma %*% Lambda

# \lambda_{ij}\lambda_{ji} = 0, i\neq j
B_G <- matrix(0, n_edges + 1, n_edges + 1)
coor_edges <- which(Lambda != 0, arr.ind = T)
coor_edges <- coor_edges[which(coor_edges[,1]!=coor_edges[,2]),]

row_ind <- rbind(c(1,2), c(2,3), c(3,4), c(2,1), c(3,2), c(0,0))
col_ind <- rbind(c(1,2), c(2,3), c(3,4), c(1,3), c(1,4), c(2,4))    # Changeable

########################################################################
Lambda <- rbind(c(0.3,0.8,0,0),c(0.4,0.5,0.7,0),c(0,0.8,0.6,0.7),c(0,0,0,0.9))
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)
Sig_Lam <- Sigma %*% Lambda
########################################################################

for (i in 1:n_edges) {
  for (j in 1:(n_edges+1)) {
    if (row_ind[i,2] == col_ind[j,1]) {
      # j = a
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,2]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,2]]
    }
    
    if (row_ind[i,2] == col_ind[j,2]) {
      # j = b
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,1]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,1]]
    }
  }
}

for (j in 1:(n_edges+1)) {
  B_G[n_edges+1,j] <- Sig_Lam[col_ind[j,1],col_ind[j,2]] * (Sig_Lam[col_ind[j,1],col_ind[j,1]] ** (-1)) + Sig_Lam[col_ind[j,2],col_ind[j,1]] * (Sig_Lam[col_ind[j,2],col_ind[j,2]] ** (-1))
}
```

```{r}
n <- 5
Lambda <- rbind(c(0.3,0.8,0,0,0),c(0.4,0.5,0.7,0,0),c(0,0.7,0.8,0.9,0),c(0,0,0.9,0.5,0.8),c(0,0,0,0.6,0.9))  # Changable coefficients
n_edges <- sum(Lambda!=0) - n

omega <- 1

# Calculate Sigma
vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
Sigma <- matrix(vec_Sigma, nrow = n)
inv_Sigma <- solve(Sigma)

Sig_Lam <- Sigma %*% Lambda

# \lambda_{ij}\lambda_{ji} = 0, i\neq j
B_G <- matrix(0, n_edges + 1, n_edges + 1)
coor_edges <- which(Lambda != 0, arr.ind = T)
coor_edges <- coor_edges[which(coor_edges[,1]!=coor_edges[,2]),]

row_ind <- rbind(c(1,2), c(2,1), c(2,3), c(3,2), c(3,4), c(4,3), c(4,5), c(5,4), c(0,0))
col_ind <- rbind(c(1,2), c(1,3), c(2,3), c(2,4), c(3,4), c(1,4), c(4,5), c(1,5), c(2,5))    # Changeable

Sig_Lam <- rbind(c(0.3,0,0,0,0),c(0,0.5,0.8,0,0.76),c(0.9,0,0.8,0.4,0),c(0.6,0,0,0.5,0),c(0,0,0,0,0.9))

for (i in 1:n_edges) {
  for (j in 1:(n_edges+1)) {
    if (row_ind[i,2] == col_ind[j,1]) {
      # j = a
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,2]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,2]]
    }
    
    if (row_ind[i,2] == col_ind[j,2]) {
      # j = b
      B_G[i,j] <- Sig_Lam[row_ind[i,1],col_ind[j,1]] * Sig_Lam[row_ind[i,2],row_ind[i,2]] - Sig_Lam[row_ind[i,1],row_ind[i,2]] * Sig_Lam[row_ind[i,2],col_ind[j,1]]
    }
  }
}

for (j in 1:(n_edges+1)) {
  B_G[n_edges+1,j] <- Sig_Lam[col_ind[j,1],col_ind[j,2]] * (Sig_Lam[col_ind[j,1],col_ind[j,1]] ** (-1)) + Sig_Lam[col_ind[j,2],col_ind[j,1]] * (Sig_Lam[col_ind[j,2],col_ind[j,2]] ** (-1))
}

```

# The study of \Sigma\Lambda

```{r}
library("ggplot2")
theme_set(theme_bw())
```


```{r}
# Initialization
n <- 2
omega <- 1
Sig_Lam_1 <- c()
Sig_Lam_2 <- c()

for (i in 1:10000) {
  Lambda <- matrix(runif(4,-1,1),2,2)
  # Calculate Sigma
  vec_Sigma <- solve(diag(n**2)-(t(Lambda) %x% t(Lambda))) %*% vec(omega * diag(n))
  Sigma <- matrix(vec_Sigma, nrow = n)

  # Calculate J
  Sig_Lam <- Sigma %*% Lambda
  
  Sig_Lam_1 <- c(Sig_Lam_1,Sig_Lam[1,2])
  Sig_Lam_2 <- c(Sig_Lam_2,Sig_Lam[2,1])
}
```

```{r}
df <- data.frame(Sig_Lam_1,Sig_Lam_2)

pt <- ggplot(df,aes(x=Sig_Lam_1,y=Sig_Lam_2))
pt + geom_point()
```

















